from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime

def generate_forensic_report(evidence, coc_chain, audit_logs, integrity_result, generator_user):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.navy,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.gray,
        alignment=TA_CENTER,
        spaceAfter=30
    )
    
    header_style = ParagraphStyle(
        'Header',
        parent=styles['Heading3'],
        fontSize=12,
        textColor=colors.navy,
        spaceBefore=15,
        spaceAfter=10,
        borderPadding=5,
        borderColor=colors.navy,
        borderWidth=1,
        borderRadius=2
    )

    normal_style = styles['Normal']
    
    # --- Title Section ---
    story.append(Paragraph("FORENSIC AUDIT REPORT", title_style))
    story.append(Paragraph("Digital Evidence Chain of Custody System", subtitle_style))
    
    # Report Metadata
    meta_data = [
        ["Report ID:", f"RPT-{datetime.utcnow().strftime('%Y%m%d')}-{evidence.id:04d}"],
        ["Generated By:", f"{generator_user.username} ({generator_user.role})"],
        ["Generation Date:", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Classification:", "CONFIDENTIAL / FORENSIC USE ONLY"]
    ]
    meta_table = Table(meta_data, colWidths=[120, 350])
    meta_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 20))

    # --- Section: Evidence Overview ---
    story.append(Paragraph("1. EVIDENCE METADATA", header_style))
    
    ev_data = [
        ["Evidence ID", str(evidence.id)],
        ["Filename", evidence.filename],
        ["Description", evidence.description],
        ["Uploader", evidence.uploader.username],
        ["Upload Timestamp", str(evidence.upload_time)],
        ["Current Status", evidence.status],
        ["Approval Status", evidence.approval_status],
        ["Encryption", "AES-256 Hybrid Encryption (Verified)"],
    ]
    
    ev_table = Table(ev_data, colWidths=[150, 320])
    ev_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
        ('BACKGROUND', (0,0), (0,-1), colors.whitesmoke),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(ev_table)
    story.append(Spacer(1, 15))

    # --- Section: Integrity Verification ---
    story.append(Paragraph("2. INTEGRITY VERIFICATION RESULT", header_style))
    
    status_color = colors.green if integrity_result['status'] == 'VERIFIED' else colors.red
    integrity_text = f"<b>INTEGRITY STATUS:</b> <font color={status_color}>{integrity_result['status']}</font>"
    story.append(Paragraph(integrity_text, styles['Normal']))
    story.append(Spacer(1, 5))
    
    int_data = [
        ["Verification Time", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Mechanism", "SHA-256 Hashing + RSA Signature Verification"],
        ["Stored Hash (Original)", Paragraph(evidence.original_hash, styles['BodyText'])],
        ["Recalculated Hash", Paragraph(integrity_result['computed_hash'], styles['BodyText'])],
        ["Signature Valid", "YES" if integrity_result['signature_valid'] else "NO (INVALID SIGNATURE)"],
        ["Hash Match", "YES" if integrity_result['hash_match'] else "NO (DATA CORRUPTION DETECTED)"]
    ]
    
    int_table = Table(int_data, colWidths=[150, 320])
    int_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
        ('BACKGROUND', (0,0), (0,-1), colors.whitesmoke),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(int_table)
    story.append(Spacer(1, 15))

    # --- Section: Chain of Custody ---
    story.append(Paragraph("3. CHAIN OF CUSTODY HISTORY", header_style))
    
    coc_headers = ["Date/Time", "Actor", "Role", "Action", "Details"]
    coc_rows = [coc_headers]
    for c in coc_chain:
        coc_rows.append([
            c.timestamp.strftime("%Y-%m-%d\n%H:%M:%S"),
            c.user.username,
            c.user.role,
            c.action,
            Paragraph(c.details or "", styles['BodyText'])
        ])
        
    coc_table = Table(coc_rows, colWidths=[80, 80, 80, 80, 150])
    coc_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.navy),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.aliceblue),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(coc_table)
    story.append(Spacer(1, 15))
    
    # --- Section: Security & Audit Logs ---
    story.append(Paragraph("4. SECURITY AUDIT LOGS (Access & Alerts)", header_style))
    
    log_headers = ["Date/Time", "User", "Action", "IP Address", "Details"]
    log_rows = [log_headers]
    for log in audit_logs:
        # Highlight tamper events
        text_color = colors.black
        if "TAMPER" in log.action or "FAILED" in log.action:
            text_color = colors.red

        log_rows.append([
            log.timestamp.strftime("%Y-%m-%d\n%H:%M:%S"),
            log.user.username,
            log.action,
            log.ip_address or "N/A",
            Paragraph(log.details or "", styles['BodyText'])
        ])
    
    if len(log_rows) > 1:
        log_table = Table(log_rows, colWidths=[80, 80, 100, 80, 130])
        log_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.darkred),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 10),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(log_table)
    else:
        story.append(Paragraph("No security alerts or additional access logs found.", normal_style))

    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph("End of Report • Generated by FOCS Secure System • Valid Signature Required", 
                 ParagraphStyle('Footer', parent=normal_style, alignment=TA_CENTER, fontSize=8, textColor=colors.gray)))

    doc.build(story)
    buffer.seek(0)
    return buffer
